name: Documentation Preview

on:
  push:
    branches:
      - staging

jobs:
  build:
    name: Docs Staging Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'


      - name: Use python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Dependencies
        run: pip3 install pipenv && pipenv install --skip-lock --clear

      - name: Build
        run: pipenv run mkdocs build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: site

  deploy:
    name: Docs Staging Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: site

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          # expires: 2d
          projectId: fetch-docs-preview
          channelId: live
          # entryPoint: docs/
